name: Latest blog post workflow
on:
  schedule:
    - cron: '55 23 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "4"
          remove_duplicates: true
          feed_list: "https://blog.christianbraeunlich.com/feed"
